import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { createClient as createServiceClient } from "@supabase/supabase-js";
import { getUserRole, canAccessAdmin } from "@/lib/admin";
import { sendNotification } from "@/lib/email";

// Bulk import of existing subscribers.
//
// These are people who are already paying through systeme.io but
// have no UnyBase account yet. We create the account for them,
// mark the subscription active so they don't get chased for a
// payment they're already making, and email them a link to set a
// password.
//
// We deliberately do NOT invent a password. The account is created
// with a random unguessable one and the client sets their own via
// a recovery link, so no plaintext credential ever exists in an
// email, a spreadsheet, or this codebase.
//
// Idempotent by email: re-running the import with the same list
// skips anyone who already exists rather than erroring, so a
// partially-failed batch can simply be run again.

type ImportResult = {
  email: string;
  status: "created" | "already_exists" | "failed";
  detail?: string;
};

function serviceClient() {
  return createServiceClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}

export async function POST(req: NextRequest) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: "unauthorized" }, { status: 401 });

  const role = getUserRole(user.email);
  if (!canAccessAdmin(role))
    return NextResponse.json({ error: "forbidden" }, { status: 403 });

  if (!process.env.SUPABASE_SERVICE_ROLE_KEY) {
    return NextResponse.json(
      { error: "SUPABASE_SERVICE_ROLE_KEY is not configured; cannot create accounts." },
      { status: 500 }
    );
  }

  const body = await req.json().catch(() => null);
  const rawEmails: unknown = body?.emails;
  if (typeof rawEmails !== "string" || !rawEmails.trim()) {
    return NextResponse.json({ error: "emails_required" }, { status: 400 });
  }

  const plan: string =
    body?.plan === "premium" ? "premium" : body?.plan === "basic" ? "basic" : "basic";
  const markActive: boolean = body?.mark_active !== false;
  const sendEmails: boolean = body?.send_emails !== false;

  // Accept commas, semicolons, whitespace or newlines as separators —
  // people paste these lists out of spreadsheets and CRMs, and the
  // separator is whatever that tool happened to use.
  const emails = Array.from(
    new Set(
      rawEmails
        .split(/[\s,;]+/)
        .map((e) => e.trim().toLowerCase())
        .filter((e) => e.includes("@") && e.length > 3)
    )
  );

  if (emails.length === 0) {
    return NextResponse.json({ error: "no_valid_emails" }, { status: 400 });
  }
  if (emails.length > 200) {
    return NextResponse.json(
      { error: "Too many at once. Import 200 or fewer per batch." },
      { status: 400 }
    );
  }

  const admin = serviceClient();
  const results: ImportResult[] = [];
  const nowIso = new Date().toISOString();

  for (const email of emails) {
    try {
      const { data: existingId } = await admin.rpc("find_user_id_by_email", {
        p_email: email,
      });
      if (typeof existingId === "string" && existingId) {
        results.push({ email, status: "already_exists" });
        continue;
      }

      // createUser goes through GoTrue rather than a raw SQL insert,
      // which means the auth row is built exactly the way the auth
      // service expects. Hand-inserting into auth.users is what
      // produced the NULL-token login failures earlier in this build.
      const { data: created, error: createErr } = await admin.auth.admin.createUser({
        email,
        password: crypto.randomUUID() + crypto.randomUUID(),
        email_confirm: true,
        user_metadata: { intended_plan: plan, imported: true },
      });

      if (createErr || !created?.user) {
        results.push({
          email,
          status: "failed",
          detail: createErr?.message ?? "unknown error",
        });
        continue;
      }

      const newId = created.user.id;

      await admin
        .from("subscription_status")
        .update({
          subscription_state: markActive ? "active" : "never_paid",
          last_payment_at: markActive ? nowIso : null,
          intended_plan: plan,
          plan_selected_at: nowIso,
          imported_from: "systeme_io_bulk",
          imported_at: nowIso,
          updated_at: nowIso,
        })
        .eq("user_id", newId);

      if (sendEmails) {
        // A recovery link doubles as a set-password link, and it is
        // generated by GoTrue so it carries a real, expiring token.
        const { data: linkData } = await admin.auth.admin.generateLink({
          type: "recovery",
          email,
        });
        const setPasswordUrl =
          linkData?.properties?.action_link ??
          `${process.env.NEXT_PUBLIC_APP_URL ?? "https://unybase.unywebs.com"}/login`;

        await sendNotification({
          to: email,
          toUserId: newId,
          template: "imported_client",
          vars: { setPasswordUrl },
          dedupeKey: `imported_client:${newId}`,
          metadata: { importedBy: user.email, plan },
        });
      }

      await admin.from("admin_actions").insert({
        admin_user_id: user.id,
        admin_email: user.email ?? "unknown",
        target_user_id: newId,
        target_email: email,
        action_type: "imported_client",
        notes: `Bulk import from systeme.io. Plan: ${plan}. Marked ${
          markActive ? "active" : "never_paid"
        }.`,
        metadata: { plan, markActive, sendEmails },
      });

      results.push({ email, status: "created" });
    } catch (e) {
      results.push({
        email,
        status: "failed",
        detail: e instanceof Error ? e.message : "unknown",
      });
    }
  }

  const summary = {
    created: results.filter((r) => r.status === "created").length,
    already_exists: results.filter((r) => r.status === "already_exists").length,
    failed: results.filter((r) => r.status === "failed").length,
  };

  return NextResponse.json({ ok: true, summary, results });
}
